namespace Nvidia.Nvml
{
    public enum NvmlReturn
    {
        NVML_SUCCESS = 0,
        NVML_ERROR_UNINITIALIZED,
        NVML_ERROR_INVALID_ARGUMENT,
        NVML_ERROR_NOT_SUPPORTED,
        NVML_ERROR_NO_PERMISSION,
        NVML_ERROR_ALREADY_INITIALIZED,
        NVML_ERROR_NOT_FOUND,
        NVML_ERROR_INSUFFICIENT_SIZE,
        NVML_ERROR_INSUFFICIENT_POWER,
        NVML_ERROR_DRIVER_NOT_LOADED,
        NVML_ERROR_TIMEOUT,
        NVML_ERROR_IRQ_ISSUE,
        NVML_ERROR_LIBRARY_NOT_FOUND,
        NVML_ERROR_FUNCTION_NOT_FOUND,
        NVML_ERROR_CORRUPTED_INFOROM,
        NVML_ERROR_GPU_IS_LOST,
        NVML_ERROR_RESET_REQUIRED,
        NVML_ERROR_OPERATING_SYSTEM,
        NVML_ERROR_LIB_RM_VERSION_MISMATCH,
        NVML_ERROR_IN_USE,
        NVML_ERROR_MEMORY,
        NVML_ERROR_NO_DATA,
        NVML_ERROR_VGPU_ECC_NOT_SUPPORTED,
        NVML_ERROR_INSUFFICIENT_RESOURCES,
        NVML_ERROR_UNKNOWN = 999
    }
}